### ISSUE TITLE
Building new CRAM package

### ISSUE THREAD

**Issue by mahyamkashani** [cram2/cram#248]
Hi,

I would like to create my own cram package. When I wanted to build my src files. I've got the following error. To resolve this issue, I usually clean the space by using clean catkin and then building all packages. I wonder whether there is any other way to build new packages without building all cram packages.

error:
> The build space at '../../roscram/cram_ws/build' was previously built by 'catkin build'. Please remove the build space or pick a different build space.

**Comment by artnie** [comment]
Workspaces can be built with `catkin_make`, which comes with the regular ROS installation, or with `catkin build`, which is an extra tool from the package `python3-catkin-tools`. I assume the error came up when you used `catkin_make`. The CRAM workspace was build with that python tool `catkin build` as indicated in the error message, therefore this workspace is bound to be built with `catkin build`. FYI this is coming from the cram-install.sh script, which uses catkin_make for the rosemacs workspace and catkin build for the CRAM workspace. 

You can build specific packages with `catkin_make --pkg <pkg-name>`. When using the python tool you can `cd` to the desired package to be built and execute `catkin build --this` instead.

Feel free to close this issue if it helped.
