### ISSUE TITLE
Fixes for environment manipulation code

### ISSUE THREAD

**Issue by gaya-** [cram2/cram#59]
* ~~In costmap calculations, instead of passing to utility functions a whole designator, only pass the URDF-NAME of container designator~~
* ~~Don't use :kitchen directly in all the environment utility functions, pass it over from the designator.~~
* ~~When converting ``urdf-name`` symbols to strings, use ``roslisp-utilities:rosify-underscores-lisp-name`` instead of simple ``string-downcase``.~~
* ~~Adjust costmaps to be further away from drawers~~
* ~~Test adjusted costmaps on real robot~~
* Implement revolute joint support
* Test revolute joints on real robot (fridge)
* ~~Check why costmaps always generate the same position when used in a navigating plan~~
* Fix the bug in costmaps for the right arm.

@cpollok

**Comment by cpollok** [comment]
- Fix it so, that when passing "iai_fridge_main" as the container, the connecting revolute joint can still be found.

**Comment by gaya-** [comment]
Revolute joints are supported. Minor issue with costmaps should be solved soon.
