### ISSUE TITLE
iai_dlr_cutting_demo does not build while installing cram system

### ISSUE THREAD

**Issue by Vanessa-rin** [cram2/cram#75]
While installing cram system from the cram-system.org/installation page, at the line
 rosdep install --ignore-src --from-paths src/

this error occurs:

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
iai_dlr_cutting_demo: Cannot locate rosdep definition for [iai_cad_downloader]

**Comment by gaya-** [comment]
For now added an explicit ``touch CATKIN_IGNORE`` into the installation guide.
