### ISSUE TITLE
cram_common/cram_tf/setup is not working with robot who are 1 handed

### ISSUE THREAD

**Issue by Vanessa-rin** [cram2/cram#78]
In the description of a robot you need to describe a robot-tool-frame for example: cram_pr2_description/src/arm-kinematics:

`
  (<- (robot-tool-frame pr2 :left "l_gripper_tool_frame"))

  (<- (robot-tool-frame pr2 :right "r_gripper_tool_frame"))`

If you don't set both of them and only one the init-tf in cram/cram_common/cram_tf/src/setup.up makes problems.

` (with-vars-bound (?torso-frame ?torso-joint)

        (lazy-car (prolog (and (robot ?robot)

       (robot-torso-link-joint ?robot ?torso-frame ?torso-joint))))

     (initialize-var *robot-torso-frame* ?torso-frame)

     (initialize-var *robot-torso-joint* ?torso-joint))`

The **and** does not work here. 

A quick fix is to set the second frame-tool to a dummy frame like 

> "please do not use this frame"

Cheers,
Vanessa-rin

**Comment by gaya-** [comment]
Solved in the boxy-melodic and boxy branches.
