### ISSUE TITLE
object-in-hand may retrieve wrong object

### ISSUE THREAD

**Issue by mpomarlan** [cram2/cram#80]
Rare, but annoying bug in BTR-BELIEF.

Situation: several objects of the same type, some of which have not been perceived.
Problem: cpoe:object-in-hand may retrieve a different object to the one grasped by the robot.

Apparent cause: (cpoe:object-designator-name ?object-designator ?object-name) branches depending on whether (cpoe:get-designator-object-name ?object-designator) returns a non-NIL ?belief-name or not. If ?belief-name is NIL, then the ?object-designator type is matched against the type of the world item selected by ?object-name. This makes it so that cpoe:object-designator-name may return a designator to an object of the same type, but a different name to ?object-name.

Suggested solution: 
(<- (cpoe:object-in-hand ?object ?side)
    (btr:bullet-world ?world)
    (cram-robot-interfaces:robot ?robot)
    (btr:attached ?world ?robot ?link ?object-name)
    (once
     (and (object-designator-name ?object ?object-name)
          (desig:desig-prop ?object (:name ?object-name))
          (desig:obj-desig? ?object)))
    (cram-robot-interfaces:end-effector-link ?robot ?side ?link))

**Comment by gaya-** [comment]
Good point, thanks for the suggestion.
I'll look into this at the next major code refactoring round.

**Comment by gaya-** [comment]
Solved in 66c503f7
