### ISSUE TITLE
Object bb costmap generator should take orientation into account

### ISSUE THREAD

**Issue by mpomarlan** [cram2/cram#85]
Currently, the make-object-bounding-box-costmap-generator function only uses the x,y pose of an object to place a rectangle in the costmap. However, this rectangle should at least be rotated by the yaw of the object.

Use case: a rectangular tray. When the tray is orthogonal to the identity position, it is very likely the robot will attempt to place items outside the tray (when it should place the items on it), because the generated costmap doesn't adjust for the difference in yaw.

Suggested fix: the returned lambda function should transform the x,y coordinates according to the tray pose. Code for this upcoming in an own branch of CRAM.

**Comment by tlipps** [comment]
This bug is now fixed and the code is merged https://github.com/cram2/cram/pull/157 into the boxy branch.
