### ISSUE TITLE
cram-urdf-projection package for any mobile manipulation robot with a urdf

### ISSUE THREAD

**Issue by gaya-** [cram2/cram#88]
Should include PR2, HSR and Boxy (and Donbot will be the test scenario when the package is ready).

* Make a list of all differences currently existing
  * Neck of boxy is an arm -- only joint interface, PR2 has only an action interface
  * Boxy gripper is commanded with CM (parallel gripper) and PR2 with radiant (rotational joint)
  * HSR has 1 arm, others have 2
* Create a new package that contains all the similar code
* Make subtasks for all the differences
* Consider the differences in the code:
  * roslaunch cram_urdf_projection setup.launch robot:=pr2_description.
  * (unless *robot-urdf*  (setf *robot-urdf* (roslisp:get-param ....))
  * ik solver independent of the robot

**Comment by Vanessa-rin** [comment]
@gaya- i think we can close this issue since ive implemented the pkg

**Comment by gaya-** [comment]
True.
